const statusOptions = [
  { name: "active", uid: "active" },
  { name: "Inactive", uid: "inactive" },
  { name: "Returned", uid: "returned" },
];

const statusOptions2 = [
  { name: false, uid: false },
  { name: true, uid: true },
];

const tableName = "Servers Table";

const columns = [
  { name: "SERVER ID", uid: "serverId", sortable: true },
  { name: "SERVER IP", uid: "serverIp", sortable: true },
  { name: "SERVER NAME", uid: "serverName", sortable: true },
  { name: "USER NAME", uid: "userName", sortable: true },
  { name: "PRO USER NAME", uid: "proUserName", sortable: true },
  { name: "PV", uid: "pv", sortable: true },
  { name: "NEW IP", uid: "newIp", sortable: true },
  { name: "ACCOUNT PROVIDER", uid: "accountProvider", sortable: true },
  { name: "CREATED AT", uid: "createdAt", sortable: true },
  { name: "PENDING", uid: "pending", sortable: true },
  { name: "STATUS", uid: "status", sortable: true },
  { name: "SERVER STATUS", uid: "serverStatus", sortable: true },
];

const dataTable = [
  {
    id:61763,
    serverId: 61763,
    serverIp: "194.87.58.130",
    serverName: "C_SF61763",
    userName: "",
    proUserName: "Mehdi Talal",
    pv: "PV37",
    newIp: "PV37",
    accountProvider: "ACC76",
    createdAt: "2024-11-14 11:08:06",
    pending: false,
    status: false,
    serverStatus: "active",
  },
  {
    id:61810,
    serverId: 61810,
    serverIp: "166.1.201.254",
    serverName: "C_SF61810",
    userName: "",
    proUserName: "Anas Youssi",
    pv: "PV446",
    newIp: "PV446",
    accountProvider: "ACC79",
    createdAt: "2024-11-14 10:42:23",
    pending: true,
    status: false,
    serverStatus: "active",
  },
  {
    id:61371,
    serverId: 61371,
    serverIp: "185.72.8.159",
    serverName: "C_SF61371",
    userName: "",
    proUserName: "abderrahim el fattouh",
    pv: "PV446",
    newIp: "PV446",
    accountProvider: "ACC79",
    createdAt: "2024-11-14 10:44:33",
    pending: true,
    status: true,
    serverStatus: "active",
  },
  {
    id:61374,
    serverId: 61374,
    serverIp: "62.76.234.134",
    serverName: "C_SF61374",
    userName: "",
    proUserName: "abderrahim el fattouh",
    pv: "PV446",
    newIp: "PV446",
    accountProvider: "ACC79",
    createdAt: "2024-11-14 10:44:33",
    pending: true,
    status: false,
    serverStatus: "active",
  },
  {
    id:61350,
    serverId: 61350,
    serverIp: "2.58.95.12",
    serverName: "C_SF61350",
    userName: "Yousra el badaoui",
    proUserName: "",
    pv: "PV37",
    newIp: "PV37",
    accountProvider: "ACC29",
    createdAt: "2024-11-14 09:26:45",
    pending: true,
    status: false,
    serverStatus: "active",
  },
  {
    id:61351,
    serverId: 61351,
    serverIp: "213.182.204.26",
    serverName: "C_SF61351",
    userName: "Yousra el badaoui",
    proUserName: "",
    pv: "PV37",
    newIp: "PV37",
    accountProvider: "ACC29",
    createdAt: "2024-11-14 09:26:45",
    pending: true,
    status: false,
    serverStatus: "active",
  },
];

const INITIAL_VISIBLE_COLUMNS = [
  "serverId",
  "serverIp",
  "serverName",
  "userName",
  "proUserName",
  "pv",
  "newIp",
  "accountProvider",
  "createdAt",
  "pending",
  "status",
  "serverStatus",
];

export { columns, dataTable, statusOptions, INITIAL_VISIBLE_COLUMNS, tableName };
